name: Generate MD5 Filesums

on:
    schedule:
      - cron: '0 */1 * * *'
    workflow_dispatch:
      inputs:
        forceGenerate:
          description: 'Force generate all md5 sums'
          default: '0'
          required: true
    push:
      branches:
        - master
      paths:
        - version.txt
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - uses: shivammathur/setup-php@v2
       with:
        php-version: '8.1'

     - name: Install xxhash
       run: |
        sudo apt-get update
        sudo apt-get install -y xxhash

     - name: Clone api-doc
       uses: actions/checkout@v2
       with:
        token: ${{ secrets.FROSH_CI_TOKEN }}

     - name: Generate Filesums
       run: |
         php generate-file-sums.php
       env:
          FORCE_GENERATE: ${{ inputs.forceGenerate }}
    
     - uses: EndBug/add-and-commit@v4
       with:
        add: '.'
        cwd: 'api-doc'
        author_name: Frosh Automation
        author_email: ci@fos.gg
        message: 'chore: Updated Filesums'
       env:
         GITHUB_TOKEN: ${{ secrets.FROSH_CI_TOKEN }}
