name: Generate MD5 Filesums

on:
    workflow_dispatch:
      inputs:
        forceGenerate:
          description: 'Force generate all md5 sums'
          default: '0'
          required: true
    push:
      branches:
        - master
      paths:
        - version.txt
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - uses: shivammathur/setup-php@v2
       with:
        php-version: '7.4'

     - name: Clone api-doc
       uses: actions/checkout@v2

     - name: Generate Filesums
       run: |
         php generate-file-sums.php
       env:
          FORCE_GENERATE: ${{ inputs.forceGenerate }}
    
     - uses: EndBug/add-and-commit@v4
       with:
        add: '.'
        author_name: Frosh Automation
        author_email: ci@fos.gg
        message: 'chore: Updated MD5 Filesums'
       env:
         GITHUB_TOKEN: ${{ secrets.FROSH_CI_TOKEN }}
